<?php

function islandora_sync_menu() {
  $items['admin/structure/types/manage/%/fedora'] = array(
    'title' => 'Fedora Commons',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_sync_bundle_settings_form', 4),
    'access arguments' => array('fedora commons export settings'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/bundle_settings.form.inc',
  );
  $items['admin/structure/types/manage/%/fields/%/fedora'] = array(
    'title' => 'Fedora Commons',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_sync_field_settings_form', 4, 6),
    'access arguments' => array('fedora commons export settings'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/field_settings.form.inc',
  );
  $items['admin/islandora/fedora-export/xml-datastreams'] = array(
    'title' => 'XML Datastream Settings',
    'page callback' => 'islandora_sync_xml_ds_page',
    'access arguments' => array('fedora commons export settings'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/xml_ds_settings.form.inc',
  );
  $items['admin/islandora/fedora-export/xml-datastreams/add'] = array(
    'title' => 'Add XML Datastream Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_sync_xml_ds_add'),
    'access arguments' => array('fedora commons export settings'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'includes/xml_ds_settings.form.inc',
  );
  $items['admin/islandora/fedora-export/xml-datastreams/%/edit'] = array(
    'title' => 'Edit XML Datastream Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_sync_xml_ds_edit', 4),
    'access arguments' => array('fedora commons export settings'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/xml_ds_settings.form.inc',
  );
  $items['admin/islandora/fedora-export/xml-datastreams/%/delete'] = array(
    'title' => 'Delete XML Datastream Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_sync_xml_ds_delete', 4),
    'access arguments' => array('fedora commons export settings'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/xml_ds_settings.form.inc',
  );
  $items['admin/islandora/fedora-export/bulk-import'] = array(
    'title' => 'Batch Import Fedora Objects',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_sync_batch_import_form'),
    'access arguments' => array('fedora commons export settings'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/import.inc',
  );
  return $items;
}

function islandora_sync_permission() {
  return array(
    'fedora commons export settings' => array(
      'title' => t('Administer Fedora Commons export settings'),
    ),
  );
}

function islandora_sync_node_insert($node) {
  $type_info = islandora_sync_bundle_settings($node->type);

  if (isset($type_info[0]->id) && $type_info[0]->sync_fedora) {
    module_load_include('inc', 'islandora', 'includes/utilities');
    $cmodels = islandora_sync_get_bundle_cmodels($type_info[0]->id);

    $namespace = $type_info[0]->namespace ?  $type_info[0]->namespace : 'default';
    $object = islandora_prepare_new_object($namespace, $node->title, array(), $cmodels, array());

    // Properly set creator
    $user = user_load($node->uid);
    $object->owner = $user->name;

    $object = islandora_add_object($object);

    // Build datastreams
    $datastreams = islandora_sync_build_datastreams($node);

    foreach ($datastreams as $ds_id => $datastream) {
      $ds = $object->constructDatastream($ds_id, 'M');
      $ds->label = $ds_id . ' Record';
      $ds->mimetype = 'text/xml';
      $ds->setContentFromString($datastream['content']);
      $object->ingestDatastream($ds);
    }
    // Log state of sync

    watchdog('mitch', 'Created object ' . $object->id);
  }

}

function islandora_sync_node_update($node) {

}

function islandora_sync_module_implements_alter(&$implementations, $hook) {
  if (($hook == 'form_field_ui_field_overview_form_alter' || $hook ==  'form_alter')
    && isset($implementations['islandora_sync'])) {
      $group = $implementations['islandora_sync'];
      unset($implementations['islandora_sync']);
      $implementations['islandora_sync'] = $group;
  }
}

function islandora_sync_form_field_ui_field_overview_form_alter(&$form, &$form_state, $form_id) {
  $form['fields']['#header'][6]['colspan'] = 3;  //@TODO: don't hardcode
  foreach ($form['fields'] AS $field_name => $values) {
    $row_types = array('field', 'extra_field', 'group');  //@TODO: must be a better way
    if (isset($values['#row_type']) && in_array($values['#row_type'], $row_types)) {
      $form['fields'][$field_name]['fedora'] = array(
        '#type' => 'link',
        '#title' => t('fedora'),
        '#href' => 'admin/structure/types/manage/' . $form['#bundle'] . '/fields/' . $field_name . '/fedora',
        '#options' => array('attributes' => array('title' => t('Manage Fedora Commons mappings.'))),
      );
    }
    elseif ($field_name[0] != '#') {
      $form['fields'][$field_name]['fedora'] = array('#markup' => '');
    }
  }
}

function islandora_sync_features_api() {
  return array(
    'field_datastreams' => array(
      'name' => t('Field to Fedora mappings'),
      'file' => drupal_get_path('module', 'islandora_sync') . '/includes/features.inc',
      //'default_hook' => 'field_datastreams_default',
      'default_file' => FEATURES_DEFAULTS_INCLUDED_COMMON,
      'feature_source' => TRUE,
    )
  );
}

function islandora_sync_get_content_models() {
  module_load_include('inc', 'islandora', 'includes/tuque');

  $connection = new IslandoraTuque();

  $query = 'select $object  $model from <#ri>
  where (walk($model <fedora-model:hasModel><info:fedora/fedora-system:ContentModel-3.0>
  and $model <fedora-model:hasModel> $object))
  minus $object <mulgara:is><info:fedora/fedora-system:FedoraObject-3.0>
  minus $object <mulgara:is><info:fedora/fedora-system:ContentModel-3.0>
  minus $object <mulgara:is><info:fedora/fedora-system:ServiceDefinition-3.0>
  minus $object <mulgara:is><info:fedora/fedora-system:ServiceDeployment-3.0>
  order by $object';

  $results = $connection->repository->ri->itqlQuery($query);

  $content_models = array();
  foreach ($results as $model) {
    $content_models[] = $model['object']['value'];
  }
  $content_models = array_unique($content_models);
  $content_models = array_values($content_models);

  return $content_models;
}

function islandora_sync_build_datastreams($node) {
  $fields = db_query("SELECT * FROM {islandora_sync_fields} WHERE bundle = :bundle AND export = 1",
    array(':bundle' => $node->type)
  )->fetchAll();

  $datastreams = array();
  foreach ($fields as $field) {
    $values = field_get_items('node', $node, $field->field); //@TODO: proper language handling
    if ($values) {
      $dsid = $field->dsid;
      if (!isset($datastreams[$dsid])) {
        $datastreams[$dsid]['type'] = $field->export_type;
        $datastreams[$dsid]['content'] = '';
      }
      foreach ($values as $value) {
        $datastreams[$dsid]['content'] = islandora_sync_build_ds_content($datastreams[$dsid]['content'], reset($value), $field);
      }
    }
  }

  return $datastreams;
}

function islandora_sync_build_ds_content($content, $node_field, $field_info) {
  switch ($field_info->export_type) {
    case 'xml_value':
      if (empty($content)) {
        $content = islandora_sync_init_xml_datastream($field_info);
      }
      $content = islandora_sync_build_xml_datastream($content, $node_field, $field_info);
      break;
    case 'managed_datastream':
      break;
  }
  return $content;
}

function islandora_sync_init_xml_datastream($field_info) {
  $ds_info = db_query('SELECT * FROM {islandora_sync_xml_ds} WHERE ds_id = :ds_id',
    array('ds_id' => $field_info->dsid)
  )->fetchAll();
  $namespaces = db_query('SELECT * FROM {islandora_sync_xml_ds_namespaces} WHERE ds_id = :ds_id',
    array('ds_id' => $field_info->dsid)
  )->fetchAll();

  $doc = new DOMDocument();
  $root = $doc->createElement($ds_info[0]->root);
  if ($ds_info[0]->namespace_uri) {
    $root->setAttribute('xmlns', $ds_info[0]->namespace_uri);
  }

  foreach ($namespaces as $namespace) {
    $root->setAttribute('xmlns:'.$namespace->prefix, $namespace->uri);
  }

  $doc->appendChild($root);
  return $doc->saveXML(); // @TODO: pass around DOMDocument rather than string
}

function islandora_sync_build_xml_datastream($content, $node_field_value, $field_info) {
  $xml_doc = new DOMDocument();
  $xml_doc->loadXML($content);
  switch ($field_info->create_type) {
    case 'element':
      $dom_xpath = new DOMXPath($xml_doc);
      $path_part = explode('/', $field_info->create_value);
      $current_path = '';
      $part_count = count($path_part);
      $parent = null;
      for ($i = 0; $i < $part_count; $i++) {
        $path = $path_part[$i];
        $value = NULL;
        if (empty($current_path)) {
          $current_path .= '/'; //@TODO: check if XML root has been provided if document context
        }
        if ($i == ($part_count - 1)) {
          $value = $node_field_value;
        }

        $current_path = $current_path . $path;
        $xpath = $dom_xpath->query($current_path);
        if (!$xpath->length) {
          // Need to create
          $namespaced = explode(':', $path);
          if (count($namespaced) > 1) {
            $ns_uri = _get_ns_uri($namespaced[0]);
            $new_element = $xml_doc->createElementNS($ns_uri, $path, $value);
          }
          else {
            $new_element = $xml_doc->createElement($path, $value);
          }
          if ($i > 0 && !is_null($parent)) {
          //@TODO: parent vs doc
            $parent->appendChild($new_element);
          }
          else {
            $xml_doc->documentElement->appendChild($new_element);
          }
          $parent = $new_element;
        }
      }
      break;
    case 'attribute':

      break;
    case 'xml':
      $value = $field_info->create_value;
      $value = str_replace('%value%', $node_field_value, $value);
      $fragment = $xml_doc->createDocumentFragment();
      $fragment->appendXML($value);
      $xml_doc->documentElement->appendChild($fragment);
      break;
  }
  $content = $xml_doc->saveXML();
  return $content;
}

function islandora_sync_get_bundle_cmodels($bundle_settings_id) {
  $cmodels = db_query("SELECT cmodel FROM {islandora_sync_type_cmodel} WHERE id = :id",
    array(':id' => $bundle_settings_id)
  )->fetchCol();
  return $cmodels;
}

function islandora_sync_bundle_settings($bundle) {
  $settings = db_query("SELECT * FROM {islandora_sync_type_settings} WHERE entity_type = 'node' AND bundle = :bundle",
    array(':bundle' => $bundle)
  )->fetchAll();
  return $settings;
}

function islandora_sync_field_settings($type, $field) {
  $settings = db_query("SELECT * FROM {islandora_sync_fields} WHERE bundle = :bundle AND field = :field",
    array(':bundle' => $type, ':field' => $field)
  )->fetchAll();
  return $settings;
}

function _get_ns_uri($namespace) {
  $ns = db_query("SELECT uri FROM {islandora_sync_xml_ds_namespaces} WHERE prefix = :prefix",
    array(':prefix' => $namespace)
  )->fetchAll();
  return $ns[0]->uri;
}

function islandora_sync_get_parent_path($field, $parents = array()) {
  $path = '';
  $parents = islandora_sync_get_parent_fields($field->field, $field->bundle, $parents);

  $parents = array_reverse($parents);
  foreach ($parents AS $parent) {
    // @TODO: field could belong to multiple bundles, query with bundle
    $field_read_path = db_query("SELECT read_path FROM {islandora_sync_fields} WHERE field = :field",
      array(':field' => $parent)
    )->fetchField();
    // @TODO: if document read context, get it and end
    if ($field_read_path && $field_read_path != $path) {
      $path .= '/' . $field_read_path;
    }
  }

  return $path;

}

//@TODO: make recursive
function islandora_sync_get_parent_fields($field, $bundle, $parents) {
  $start_count = count($parents);
  $field_info = field_info_instance('node', $field, $bundle);

  // is part of field_collection? has to be a better way to do this
  // entity_type == field_collection_item ?? in field_config_instance
  // check if module exists?
  if ($field_info['widget']['module'] == 'field_collection') {

  }
  elseif (module_exists('field_group')) { // could be disabled
    // is part of field_group?
    // this is also terrible
    ctools_include('export');
    $groups = ctools_export_load_object('field_group', 'conditions', array(
      'entity_type' => 'node',
      'bundle' => $bundle,
    ));
    foreach ($groups as $group) {
      if (in_array($field, $group->data['children'])) {
        $parents[] = $group->group_name;
        if ($group->parent_name) {
          $parents[] = $group->parent_name;
        }
      }
    }
  }

  $current_count = count($parents);
  if ($current_count > $start_count) {
    $parents = islandora_sync_get_parent_fields($parents[$current_count -1], $bundle, $parents);
  }

  return $parents;
}