<?php

/**
 * Implements hook_menu().
 */
function islandora_sync_batch_menu() {
  $items = array();
  $items['admin/islandora/sync/bulk-import'] = array(
    'title' => 'Batch Import Fedora Objects',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_sync_batch_import_form'),
    'access arguments' => array('islandora sync batch'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function islandora_sync_permission() {
  return array(
    'islandora sync batch' => array(
      'title' => t('Use Islandora sync batch'),
    ),
  );
}

function islandora_sync_batch_import_form($form, $form_state) {
  $form = array();

  $form['pid'] = array(
    '#type' => 'textfield',
    '#title' => t('Pid'),
  );

  $form['node_type'] = array(
    '#type' => 'radios',
    '#title' => t('Node type'),
    '#options' => node_type_get_names(),
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
  return $form;
}

function islandora_sync_batch_import_form_validate($form, $form_state) {
  module_load_include('inc', 'islandora', 'includes/utilities');
  if (!islandora_is_valid_pid($form_state['values']['pid'])) {
    form_set_error('pid', t('Please enter a valid PID'));
  }
}

function islandora_sync_batch_import_form_submit($form, $form_state) {
  islandora_sync_import_batch(array($form_state['values']['pid']), $form_state['values']['node_type']);
}

function islandora_sync_import_batch($pids, $type) {
  module_load_include('inc', 'islandora_sync', 'includes/import_to_drupal');
  foreach ($pids as $pid) {
    $node_id = islandora_sync_import_from_pid($pid, $type);
    drupal_set_message(t('Imported object: @pid to node/@id', array('@pid' => $pid, '@id' => $node_id)));
  }
}